package lk.dialog.pe.ccbs.util;

public enum SQLQueryEnum {

	/* IP 500  */
	SQL_DBN_ACCOUNT_NUM_BY_INVOICE_NO("SQL_DBN_ACCOUNT_NUM_BY_INVOICE_NO"),
	SQL_CCBS_SYSTEM_QRY_CONTRACT("SQL_CCBS_SYSTEM_QRY_CONTRACT"),
	SQL_CCBS_SYSTEM_QRY_CONREF("SQL_CCBS_SYSTEM_QRY_CONREF"),
	SQL_CCBS_PROFILE_BY_INVOICE_NO("SQL_CCBS_PROFILE_BY_INVOICE_NO"),
	SQL_CCBS_VOLTE_PROFILE_BY_ID("SQL_CCBS_VOLTE_PROFILE_BY_ID"),
	SQL_CCBS_ACCOUNT_NO_BY_INVOICE_NO("SQL_CCBS_ACCOUNT_NO_BY_INVOICE_NO"),
	SQL_CCBS_PROFILE_BY_ID("SQL_CCBS_PROFILE_BY_ID"),
	SQL_WIFI_PROFILE_BY_ID("SQL_WIFI_PROFILE_BY_ID"),
	SQL_NFC_EMAIL_BY_CONTRACT("SQL_NFC_EMAIL_BY_CONTRACT"),
	SQL_NFC_WIFI_ACCOUNT_NO_BY_INVOICE_NO("SQL_NFC_WIFI_ACCOUNT_NO_BY_INVOICE_NO"),
	SQL_CCBS_PROFILE_BY_MSISDN("SQL_CCBS_PROFILE_BY_MSISDN"),
	SQL_CCBS_PROFILE_BY_CONTRACT("SQL_CCBS_PROFILE_BY_CONTRACT"),
	SQL_DCS_PROFILE_BY_MSISDN("SQL_DCS_PROFILE_BY_MSISDN"),
	SQL_DCS_PROFILE_BY_CONTRACT("SQL_DCS_PROFILE_BY_CONTRACT"),
	SQL_WIFI_PROFILE_BY_CONTRACT("SQL_WIFI_PROFILE_BY_CONTRACT"),
	SQL_WIFI_PROFILE_BY_CONNECTION_REF("SQL_WIFI_PROFILE_BY_CONNECTION_REF"),
	
	/* 503 */
	SQL_CONTRACT_BY_MOBILE("SQL_CONTRACT_BY_MOBILE"),
	SQL_MOBILE_BY_CONTRACT("SQL_MOBILE_BY_CONTRACT"),
	
	/*505*/
	SQL_MAP_CPOS_PAYMODE_FOR_RBM("SQL_MAP_CPOS_PAYMODE_FOR_RBM"),
	SQL_MAP_CPOS_PAYMODE("SQL_MAP_CPOS_PAYMODE"),
	SQL_DCS_SBU_BY_CONTRACT_ID("SQL_DCS_SBU_BY_CONTRACT_ID"),
	SQL_CCBS_SBU_BY_CONTRACT_ID("SQL_CCBS_SBU_BY_CONTRACT_ID"),
	SQL_MAP_PAYMODE("SQL_MAP_PAYMODE"),
	
	/*512*/
	SQL_OCS_PAYMENT_POST("SQL_OCS_PAYMENT_POST"),
	SQL_CHQ_FORCEFUL_REALIZE("SQL_CHQ_FORCEFUL_REALIZE"),
	
	/*501*/
	SQL_WIFI_CONTRACT_BY_MOBILE("SQL_WIFI_CONTRACT_BY_MOBILE"),
	SQL_DCS_MOBILE_BY_CONTRACT("SQL_DCS_MOBILE_BY_CONTRACT"),
	
	/*511*/
	SQL_PAYMENT_NEXT_SEQ("SQL_PAYMENT_NEXT_SEQ"),
	SQL_PAYMENT_CANCEL("SQL_PAYMENT_CANCEL"),
		
	/* 504 */
	SQL_HOTLINE_REMARKS("SQL_HOTLINE_REMARKS"),
	SQL_CCBS_WIFI_REMARKS("SQL_CCBS_WIFI_REMARKS"),
	SQL_DCS_REMARKS("SQL_DCS_REMARKS"),
	
	/*506*/
	
	/*510*/	
	SQL_RBM_PAYMENT_POST("SQL_RBM_PAYMENT_POST");
	
	
	
	private final String value;
	
	SQLQueryEnum(String value) {
			this.value = value;
	}

	public String getValue() {
		return value;
	}
	
	
}
